---
- name: Prepare Ec2 as Agent
  hosts: all
  become: yes
  tasks:
    - name: Create myagent directory
      file:
        path: /home/{{ ansible_user }}/myagent
        state: directory

    - name: Download agent package using curl
      command: >
        curl -L -o /home/{{ ansible_user }}/myagent/vsts-agent-linux-x64-4.254.0.tar.gz
        https://vstsagentpackage.azureedge.net/agent/4.254.0/vsts-agent-linux-x64-4.254.0.tar.gz
      args:
        creates: /home/{{ ansible_user }}/myagent/vsts-agent-linux-x64-4.254.0.tar.gz

    - name: Extract the file
      unarchive:
        src: /home/{{ ansible_user }}/myagent/vsts-agent-linux-x64-4.254.0.tar.gz
        dest: /home/{{ ansible_user }}/myagent
        remote_src: yes

    - name: Update apt package list
      apt:
        update_cache: yes

    - name: Add DeadSnakes PPA manually
      shell: |
        sudo add-apt-repository -y ppa:deadsnakes/ppa
        sudo apt-get update
    
    - name: Install Python 3.9 and dependencies
      apt:
        name:
          - python3.9
          - python3.9-dev
          - python3.9-venv
        state: present

    - name: Install Docker dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - software-properties-common
        state: present

    - name: Install required packages
      apt:
        name:
          - ca-certificates
          - curl
        state: present
        update_cache: yes

    - name: Create keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
        
    - name: Download Docker GPG key using curl
      shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
      args:
        creates: /etc/apt/keyrings/docker.asc


    - name: Add Docker apt repository
      copy:
        dest: /etc/apt/sources.list.d/docker.list
        content: |
          deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable
        mode: '0644'

    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes


    - name: Download kubectl
      shell: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      args:
        chdir: /tmp

    - name: Install kubectl
      command: >
        sudo install -o root -g root -m 0755 /tmp/kubectl /usr/local/bin/kubectl

    - name: Remove the downloaded kubectl binary
      file:
        path: /tmp/kubectl
        state: absent

    - name: Download AWS CLI v2 using curl
      shell: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"
      args:
        creates: /tmp/awscliv2.zip
        
    - name: Unzip AWS CLI
      unarchive:
        src: "/tmp/awscliv2.zip"
        dest: "/tmp"
        remote_src: yes

    - name: Install AWS CLI
      command: /tmp/aws/install
      args:
        creates: /usr/local/bin/aws

    - name: Verify AWS CLI Installation
      command: aws --version
      register: aws_cli_version

    - name: Show AWS CLI Version
      debug:
        var: aws_cli_version.stdout
